version: 2.1
jobs:
#  build:
#    docker:
#      - image: circleci/node:9.11
#    steps:
#      - checkout
#      - run:
#          name: The First Step
#          command: |
#            echo 'Hello World!'
#            echo 'This is the delivery pipeline'
#      - run:
#          name: Code Has Arrived
#          command: |
#            ls -al
#            echo '^^^That should look familiar^^^'
#      - run:
#          name: Running in a Unique Container
#          command: |
#            node -v
#      - run:
#          name: Install tests
#          command: |
#            cd exercises
#            npm install
  test:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - run:
          name: Test
          command: |
            cd exercises
            npm install
            npm test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
